In [5]:
import pandas as pd
import numpy as np


import seaborn as sns                       #visualisation
import matplotlib.pyplot as plt             #visualisation

file = "C:/Users/TYS/Documents/study/Master/MGSC662/group project/MGSC-662-FIFA-Project/data/players_22.csv"
#file = "players_22.csv"
try:
    data = pd.read_csv(file, encoding='ISO-8859-1')
except UnicodeDecodeError:
    # If 'ISO-8859-1' fails, try with 'windows-1252' encoding
    try:
        data = pd.read_csv(file, encoding='windows-1252')
    except UnicodeDecodeError as e:
        # If both encodings fail, raise the error
        raise e

# Display the first few rows of the dataframe
data.head()

C:\Users\TYS\AppData\Local\Temp\ipykernel_28404\1065511209.py:11: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file, encoding='ISO-8859-1')

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url,Unnamed: 110
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel AndrÃ©s Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png,NaN
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png,NaN
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png,NaN
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos JÃºnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png,NaN
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png,NaN

In [6]:
data.head()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url,Unnamed: 110
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel AndrÃ©s Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png,NaN
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png,NaN
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png,NaN
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos JÃºnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png,NaN
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png,NaN

In [7]:
# Check for missing values
missing_values = data.isnull().sum()

# Check for duplicate rows
duplicates = data.duplicated().sum()

# Check for columns with mixed data types
mixed_types = {col: data[col].apply(type).nunique() for col in data.columns if data[col].apply(type).nunique() > 1}

# Summarize the findings
missing_values_summary = missing_values[missing_values > 0]
mixed_types_summary = {col: types for col, types in mixed_types.items() if types > 1}

(missing_values_summary, duplicates, mixed_types_summary)

(value_eur                       74
 wage_eur                        61
 club_team_id                    61
 club_name                       61
 league_name                     61
 league_level                    61
 club_position                   61
 club_jersey_number             264
 club_loaned_from             17847
 club_joined                   1248
 club_contract_valid_until       63
 nationality_name               206
 nation_team_id               18382
 nation_position              18480
 nation_jersey_number         18274
 preferred_foot                  98
 real_face                       10
 release_clause_eur            1374
 player_tags                  17641
 player_traits                 9807
 pace                          2183
 shooting                      2132
 passing                       2132
 dribbling                     2132
 defending                     2132
 physic                        2064
 goalkeeping_reflexes           145
 goalkeeping_speed            16863
 ls                              99
 club_logo_url                   61
 club_flag_url                  267
 nation_logo_url              18176
 nation_flag_url                311
 Unnamed: 110                 19140
 dtype: int64,
 0,
 {'club_team_id': 2,
  'club_name': 2,
  'league_name': 2,
  'league_level': 2,
  'club_position': 2,
  'club_jersey_number': 2,
  'club_loaned_from': 2,
  'club_joined': 2,
  'club_contract_valid_until': 2,
  'nationality_name': 2,
  'nation_team_id': 2,
  'nation_position': 2,
  'nation_jersey_number': 2,
  'preferred_foot': 2,
  'real_face': 2,
  'release_clause_eur': 2,
  'player_tags': 2,
  'player_traits': 2,
  'pace': 2,
  'goalkeeping_speed': 2,
  'ls': 2,
  'club_logo_url': 2,
  'club_flag_url': 2,
  'nation_logo_url': 2,
  'nation_flag_url': 2,
  'Unnamed: 110': 2})

In [ ]:
# List of columns to drop
columns_to_drop = [
     'player_url', 'long_name', 'player_face_url', 
    'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 
    'Unnamed: 110'
]

# Additionally, drop columns with more than 50% missing values
columns_to_drop.extend(missing_values[missing_values > (data.shape[0] / 2)].index.tolist())

# Drop the columns
data_cleaned = data.drop(columns=columns_to_drop, errors='ignore')

# Verify the drop operation
data_cleaned.info()

In [11]:
data_cleaned

,sofifa_id,short_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,158023,L. Messi,"RW, ST, CF",93,93,78000000.0,320000.0,34,1987/6/24,170,...,64+3,64+3,64+3,66+3,61+3,50+3,50+3,50+3,61+3,19+3
1,188545,R. Lewandowski,ST,92,92,119500000.0,270000.0,32,1988/8/21,185,...,66+3,66+3,66+3,64+3,61+3,60+3,60+3,60+3,61+3,19+3
2,20801,Cristiano Ronaldo,"ST, LW",91,91,45000000.0,270000.0,36,1985/2/5,187,...,59+3,59+3,59+3,63+3,60+3,53+3,53+3,53+3,60+3,20+3
3,190871,Neymar Jr,"LW, CAM",91,91,129000000.0,270000.0,29,1992/2/5,175,...,63+3,63+3,63+3,67+3,62+3,50+3,50+3,50+3,62+3,20+3
4,192985,K. De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,1991/6/28,181,...,80+3,80+3,80+3,79+3,75+3,69+3,69+3,69+3,75+3,21+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,261962,Song Defu,47,52,70000,1000.0,22.0,1999/1/2,180,64,...,46+2,46+2,48+2,48+2,46+2,46+2,46+2,48+2,15+2,https://cdn.sofifa.net/players/261/962/22_120.png
19235,262040,C. Porter,CM,47,59,110000.0,500.0,19,2002/3/18,175,...,46+2,46+2,46+2,49+2,48+2,44+2,44+2,44+2,48+2,14+2
19236,262760,N. Logue,CM,47,55,100000.0,500.0,21,2000/2/7,178,...,46+2,46+2,46+2,47+2,47+2,45+2,45+2,45+2,47+2,12+2
19237,262820,L. Rudden,ST,47,60,110000.0,500.0,19,2002/4/23,173,...,29+2,29+2,29+2,33+2,32+2,26+2,26+2,26+2,32+2,15+2
19238,264540,E. Lalchhanchhuaha,CAM,47,60,110000.0,500.0,19,2002/2/6,167,...,44+2,44+2,44+2,45+2,45+2,41+2,41+2,41+2,45+2,16+2

In [13]:
# Identify rows with numerical values in "player_positions"
rows_with_numerical_positions = data_cleaned['player_positions'].str.contains('\d', regex=True)

# Count the number of such rows
numerical_positions_count = rows_with_numerical_positions.sum()

# Drop rows with numerical values in "player_positions"
data_cleaned = data_cleaned[~rows_with_numerical_positions]

data_cleaned

,sofifa_id,short_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,158023,L. Messi,"RW, ST, CF",93,93,78000000.0,320000.0,34,1987/6/24,170,...,64+3,64+3,64+3,66+3,61+3,50+3,50+3,50+3,61+3,19+3
1,188545,R. Lewandowski,ST,92,92,119500000.0,270000.0,32,1988/8/21,185,...,66+3,66+3,66+3,64+3,61+3,60+3,60+3,60+3,61+3,19+3
2,20801,Cristiano Ronaldo,"ST, LW",91,91,45000000.0,270000.0,36,1985/2/5,187,...,59+3,59+3,59+3,63+3,60+3,53+3,53+3,53+3,60+3,20+3
3,190871,Neymar Jr,"LW, CAM",91,91,129000000.0,270000.0,29,1992/2/5,175,...,63+3,63+3,63+3,67+3,62+3,50+3,50+3,50+3,62+3,20+3
4,192985,K. De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,1991/6/28,181,...,80+3,80+3,80+3,79+3,75+3,69+3,69+3,69+3,75+3,21+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19233,261818,R. Gallagher,CAM,47,61,110000.0,500.0,20,2001/5/11,180,...,42+2,42+2,42+2,41+2,41+2,39+2,39+2,39+2,41+2,15+2
19235,262040,C. Porter,CM,47,59,110000.0,500.0,19,2002/3/18,175,...,46+2,46+2,46+2,49+2,48+2,44+2,44+2,44+2,48+2,14+2
19236,262760,N. Logue,CM,47,55,100000.0,500.0,21,2000/2/7,178,...,46+2,46+2,46+2,47+2,47+2,45+2,45+2,45+2,47+2,12+2
19237,262820,L. Rudden,ST,47,60,110000.0,500.0,19,2002/4/23,173,...,29+2,29+2,29+2,33+2,32+2,26+2,26+2,26+2,32+2,15+2
19238,264540,E. Lalchhanchhuaha,CAM,47,60,110000.0,500.0,19,2002/2/6,167,...,44+2,44+2,44+2,45+2,45+2,41+2,41+2,41+2,45+2,16+2

In [15]:
# Identify rows in the "overall" column that contain non-numeric values
rows_with_non_numeric_overall = data_cleaned['overall'].str.isnumeric() == False

# Count the number of such rows
non_numeric_overall_count = rows_with_non_numeric_overall.sum()

# Drop rows with non-numeric values in "overall"
data_cleaned = data_cleaned[~rows_with_non_numeric_overall]

# Show the number of rows identified and dropped
data_cleaned

,sofifa_id,short_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,158023,L. Messi,"RW, ST, CF",93,93,78000000.0,320000.0,34,1987/6/24,170,...,64+3,64+3,64+3,66+3,61+3,50+3,50+3,50+3,61+3,19+3
1,188545,R. Lewandowski,ST,92,92,119500000.0,270000.0,32,1988/8/21,185,...,66+3,66+3,66+3,64+3,61+3,60+3,60+3,60+3,61+3,19+3
2,20801,Cristiano Ronaldo,"ST, LW",91,91,45000000.0,270000.0,36,1985/2/5,187,...,59+3,59+3,59+3,63+3,60+3,53+3,53+3,53+3,60+3,20+3
3,190871,Neymar Jr,"LW, CAM",91,91,129000000.0,270000.0,29,1992/2/5,175,...,63+3,63+3,63+3,67+3,62+3,50+3,50+3,50+3,62+3,20+3
4,192985,K. De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,1991/6/28,181,...,80+3,80+3,80+3,79+3,75+3,69+3,69+3,69+3,75+3,21+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19233,261818,R. Gallagher,CAM,47,61,110000.0,500.0,20,2001/5/11,180,...,42+2,42+2,42+2,41+2,41+2,39+2,39+2,39+2,41+2,15+2
19235,262040,C. Porter,CM,47,59,110000.0,500.0,19,2002/3/18,175,...,46+2,46+2,46+2,49+2,48+2,44+2,44+2,44+2,48+2,14+2
19236,262760,N. Logue,CM,47,55,100000.0,500.0,21,2000/2/7,178,...,46+2,46+2,46+2,47+2,47+2,45+2,45+2,45+2,47+2,12+2
19237,262820,L. Rudden,ST,47,60,110000.0,500.0,19,2002/4/23,173,...,29+2,29+2,29+2,33+2,32+2,26+2,26+2,26+2,32+2,15+2
19238,264540,E. Lalchhanchhuaha,CAM,47,60,110000.0,500.0,19,2002/2/6,167,...,44+2,44+2,44+2,45+2,45+2,41+2,41+2,41+2,45+2,16+2

In [17]:
data_cleaned.to_csv('C:/Users/TYS/Documents/study/Master/MGSC662/group project/MGSC-662-FIFA-Project/data/players_22_cleaned.csv', index=False)